Add testcases for PersonCard, ViewPersonCard and ViewCommand
AY2425S1-CS2103T-F11-2/tp pull request #170
Opened 2024-11-05 17:07 UTC by superb-sushi

2024-11-06 01:23 UTC, weiliann submitted a review, later dismissed

2024-11-06 01:24 UTC, weiliann requested changes
the build is failing for ubuntu os

2024-11-06 06:03 UTC, weiliann approved these changes

2024-11-07 02:30 UTC, yyihaoc approved these changes
LGTM

2024-11-07 02:30 UTC, shizy approved these changes
LGTM

2024-11-07 02:30 UTC, merged