Change `add` command to reflect telegram username instead of address
AY2425S1-CS2103T-F11-2/tp pull request #46
Opened 2024-10-10 12:20 UTC by shizy

Removed address, replacing it with telegram.

Note that tags have not been fully converted into roles yet (To be done in due time)

2024-10-10 19:50 UTC, weiliann requested changes
![image](https://github.com/user-attachments/assets/38869633-f5ae-411f-aec6-49489275f2eb)

There's a small bug. The example provided doesnt work. i believe it's because the 'role' field currently cant accept white spaces

2024-10-10 19:50 UTC, weiliann commented on src/main/java/seedu/address/logic/commands/AddCommand.java
> +import static seedu.address.logic.parser.CliSyntax.PREFIX_TELEGRAM;
The import order is triggering the checkstyle checks. on windows we can use the shortcut ctrl-alt-o to organize the imports, not sure about mac

2024-10-11 04:16 UTC, superb-sushi approved these changes
LGTM

2024-10-11 04:18 UTC, weiliann approved these changes

2024-10-11 04:18 UTC, merged